{
 "title": "PCM_Dashboard",
 "description": "Processor Counter Monitor (PCM) Sensor Server Dashboard",
 "time": { "from": "2022-10-05T19:03:24.500Z", "to": "2022-10-05T19:32:41.377Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(Number_of_sockets, instance)"
    }
   },
   { "name": "socket", "label": "Socket:", "query": { "query": "label_values(socket)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} DRAM Read"
    },
    {
     "expr": "rate(DRAM_Writes{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} DRAM Write"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} PMM Read"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} PMM Write"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "rate(Local_Memory_Bandwidth{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Local"
    },
    {
     "expr": "rate(Remote_Memory_Bandwidth{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Remote"
    }
   ]
  },
  {
   "title": "Interconnect Outgoing Data And Non-Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Link 0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Link 1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Link 2"
    }
   ]
  },
  {
   "title": "Interconnect Incoming Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Link 0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Link 1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} Link 2"
    }
   ]
  },
  {
   "title": "Instructions Per Cycle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])/rate(Clock_Unhalted_Thread{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}}"
    }
   ]
  },
  {
   "title": "Active Frequency Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])/rate(Clock_Unhalted_Ref{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}}"
    }
   ]
  },
  {
   "title": "L2 Cache Misses Per Instruction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])/rate(Instructions_Retired_Any{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}}"
    }
   ]
  },
  {
   "title": "L3 Cache Misses Per Instruction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])/rate(Instructions_Retired_Any{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}}"
    }
   ]
  },
  {
   "title": "L2 Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(L2_Cache_Hits{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]) / (rate(L2_Cache_Hits{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]) + rate(L2_Cache_Misses{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]))",
     "legendFormat": "Socket {{socket}}"
    }
   ]
  },
  {
   "title": "L3 Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(L3_Cache_Hits{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]) / (rate(L3_Cache_Hits{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]) + rate(L3_Cache_Misses{aggregate=\"socket\", instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]))",
     "legendFormat": "Socket0"
    }
   ]
  },
  {
   "title": "Core C-state residency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(RawCStateResidency{source=\"core\",aggregate=\"socket\",instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]) / ignoring(index) group_left rate(Invariant_TSC{source=\"core\",aggregate=\"socket\",instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} C{{index}}"
    }
   ]
  },
  {
   "title": "Package C-state residency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(RawCStateResidency{source=\"uncore\",instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval]) / ignoring(index,source,aggregate) group_left rate(Invariant_TSC{source=\"core\",aggregate=\"socket\",instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} C{{index}}"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} CPU"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{instance=\"$node\",socket=~\"${socket}\"}[$__rate_interval])",
     "legendFormat": "Socket {{socket}} DRAM"
    }
   ]
  }
 ]
}