#!/usr/bin/env python
"""
Created on: 12/12/2024 11:04

Author: Shyam Bhuller (University of Oxford)

Description: Calculate key value metrics for the performance tests and create plots showing them.
"""
import argparse
import ast
import os

from collections import namedtuple
from enum import Enum
from types import SimpleNamespace

import files, shell, plotting, utils, times, cpu_topology
from times import time_range
import matplotlib.patches as mpatches

import numpy as np
import pandas as pd

from rich import print

np.seterr(divide='ignore', invalid='ignore')

class ReadoutPlane(Enum):
    APA = 4
    CRP = 2

ReadoutPlaneValues = namedtuple("ReadoutPlaneValues", ["num_channels", "adc_sampling_rate", "adc_size", "num_rp_fd", "snb_readout_time", "readout_window", "tp_rate", "tp_size", "max_disk_write", "num_wibs", "num_nics", "channels_per_queue"])

readout_plane_values = {
    ReadoutPlane.APA : ReadoutPlaneValues(num_channels = 2560, adc_sampling_rate = 1.953125E6, adc_size = 14, num_rp_fd = 150, snb_readout_time = 100, readout_window = 2.6, tp_rate = [100, 500], tp_size = 384, max_disk_write = 12, num_wibs = 5, num_nics = 8, channels_per_queue = 256),
    ReadoutPlane.CRP : ReadoutPlaneValues(num_channels = 3072, adc_sampling_rate = 1.953125E6, adc_size = 14, num_rp_fd = 160, snb_readout_time = 100, readout_window = 4.25, tp_rate = [100, 500], tp_size = 384, max_disk_write = 13.5, num_wibs = 6, num_nics = 8, channels_per_queue = 256), # max disk write is dependant on the storage device
}

def sum_over_app(df : pd.DataFrame, app_names : list[str]):
    merged = {}
    for i in app_names:
        for j in df.columns:
            if i in j:
                if i not in merged:
                    merged[i] = df[j]
                else:
                    merged[i] = merged[i] + df[j]
    return pd.DataFrame(merged)

def memory_bw_info_AMD(df : pd.DataFrame) -> pd.DataFrame:
    """ Retreive and format memory bandwidth utilization for AMD servers.

    Args:
        df (pd.DataFrame): uProf data.

    Returns:
        pd.DataFrame: Memory bandwidth data.
    """
    mem_data = df.filter(regex = "(?=.*Total Mem)") * 1E9 # get memory per socket (exclude per DIMM)

    new_columns = {}
    for i in mem_data.columns:
        new = i.replace("Total Mem ", "").replace("RdBw", "Read").replace("WrBw", "Write").replace("Bw", "Read + Write") # format column names
        new = new.split(" (")[0] + new.split(")")[-1] # remove units (added in y label later)
        new_columns[i] = new

    mem_data = mem_data.rename(columns = new_columns)
    return mem_data


def memory_bw_info_Intel(df : pd.DataFrame) -> pd.DataFrame:
    """ Retreive and format memory bandwidth utilization for Intel servers.

    Args:
        df (pd.DataFrame): pcm data.

    Returns:
        pd.DataFrame: Memory bandwidth data.
    """
    mem_data = utils.search_dict(df, "(?=.*Mem)(?=.*MByte)") # get bandwidth with known units
    mem_data = {k : v.filter(regex = "^(?!.*Total)^(?!.*Persistent)") * 1E6 for k, v in mem_data.items()} # will not keep socket 0 + 1 bandwidth (provided by node exporter)

    mem_data_rw = list(utils.search_dict(mem_data, "^(?!.*Current)").values())[0] # get read + write bandwidth per socket
    mem_data_rw = mem_data_rw.rename(columns = lambda x: f"Read + Write {x}")
    mem_data = utils.search_dict(mem_data, "(?=.*Current)") # get read and write bandwidth separately per socket

    # restructure data into single dataframe
    fmt_df = []
    for k, v in mem_data.items():
        socket = "Socket"+k.split("Socket")[-1].split(" ")[0]
        fmt_df.append(v.rename(columns=lambda x: x.replace("DRAM Reads", f"Read {socket}")).rename(columns=lambda x: x.replace("DRAM Writes", f"Write {socket}")))
    return pd.concat(fmt_df + [mem_data_rw], axis = 1)


def calculate_maximum_memory_bw(hardware_info : str) -> float | None:
    """ Calculate the maximum available memory bandwidth per socket.
        Assumes that the DIMMs are all the same, there are an equal number of DIMMs per socket.
        Only works if the lshw file was generated by a sudo user.
        #* memory speed(T/s)/2 * bytes of width * nchannels available / number of sockets (assuming uniform allocation)
        https://www.intel.com/content/www/us/en/support/articles/000056722/processors/intel-core-processors.html

    Args:
        hardware_info (str): xml description of the host machine.

    Returns:
        float | None: calculated maximum bandwidth. Returns None if the value cannot be calculted.
    """
    tree = files.read_xml(hardware_info)
    n_dimms = 0
    data_width = None
    clock_speed = None
    for i in utils.xml_search_elem(tree, "class", "memory"):
        if "bank" in i.attrib["id"]: # this is a DIMM
            description = utils.xml_search_elem_name_single(i, "description")
            if '[empty]' not in description.text: # DIMM is populated
                n_dimms += 1
                width = utils.xml_search_elem_name_single(i, "width")
                speed = utils.xml_search_elem_name_single(i, "clock")
                #* assume all DIMMs are the same specifications (they should be...)
                if width is not None: data_width = int(width.text) # this is in bits
                #! this output is currently bugged in lshw and affects DDR5 memory https://project.ezix.org/ticket/836
                # if speed is not None: clock_speed = int(speed.text) # this is in Hz
                #! instead, get the clock speed from the description for now
                words = description.text.split(" ")
                clock_speed = int(words[words.index("MHz") - 1]) * 1E6 # in Hz
    n_channels = n_dimms/2

    if not data_width:
        print("Warning: lshw information does not contain detailed information about the DRAM.")
        return
    else:
        n_sockets = len(list([i for i in utils.xml_search_elem(tree, "class", "processor") if "cpu" in i.attrib["id"]]))
        return (data_width//8) * clock_speed * n_channels / n_sockets


def process_memory_info(ne : pd.DataFrame, intel : pd.DataFrame | None, amd : pd.DataFrame | None, out : str, hw_info : str, test_args : dict, host : str):
    """ Process metrics for system memory and plot them.

    Args:
        ne (pd.DataFrame): Node exporter data.
        intel (pd.DataFrame | None): Intel pcm data.
        amd (pd.DataFrame | None): AMD uProf data.
        out (str): Output plot directory.
        hw_info (str): Hardware information file path about the host machine.
        test_args (dict): Test configuration arguments.
        host (str): Host machine name.
    """
    intel_data = None
    amd_data = None

    if intel is not None:
        if all([i.empty for i in utils.search_dict(intel, f"(?=Mem)").values()]):
            print("no Intel PCM data captured")
        else:
            intel_data = memory_bw_info_Intel(intel)
    
    if amd is not None:
        if all([i.empty for i in utils.search_dict(amd, f"(?=Mem)").values()]):
            print("no AMD uProf data captured")
        else:
            amd_data = memory_bw_info_AMD(amd)

    with plotting.PlotBook(out + f"memory_plots_{host}.pdf") as book:
        mem_usg = ne["Memory Usage (%)"]
        if mem_usg.empty:
            print("Warning : no system memory information was found.")
        else:
            tlabel = "Relative time (s)"
            plotting.plot(times.relative_time(mem_usg), mem_usg, None, tlabel, "Memory Usage (%)")
            # plotting.plt.axhline(80, color = "k", linestyle = "--")
            # plotting.plt.ylim(0, 100)
            plotting.add_metadata(test_args, int(mem_usg.index[0]), host = host)
            book.save()

        for i in [intel_data, amd_data]:
            if i is None: continue
            if "lshw" in hw_info:
                bw = calculate_maximum_memory_bw(hw_info["lshw"])
            else:
                print("Note: maximum memery bandwidth of server cannot be calculated, lshw output was not captured.")
                bw = None

            plotting.plot(times.relative_time(i), i, i.columns, "Relative time (s)", "Memory bandwidth Usage", autofmt = "B/s")
            # if bw: plotting.hline(bw, label = "maximum bandwidth", autofmt = "B/s", linestyle = "--")
            plotting.plt.legend(fontsize = "x-small")
            plotting.add_metadata(test_args, int(i.index[0]))
            book.save()

            if bw:
                plotting.plot(times.relative_time(i), 100 * i/bw, i.columns, "Relative time (s)", "Memory bandwidth Usage (%)")
                plotting.plt.legend(fontsize = "x-small")
                plotting.add_metadata(test_args, int(i.index[0]))
                book.save()
    return


def cache_info_Intel(df : pd.DataFrame) -> list[dict]:
    """ Retrieve L2 and L3 accesses (hits and misses) and calculate percentages for Intel servers.

    Args:
        df (pd.DataFrame): pcm data.

    Returns:
        list[dict]: L2/3 access counts and access percentages.
    """
    access = {}
    access_percent = {}

    for i in [2, 3]:
        cache_data = utils.search_dict(df, f"(?=L{i})") # get the cache data
        acc = utils.search_dict(cache_data, f"(?=.*Million)") # get the access counts

        for k, v in acc.items():
            for t in ["Miss", "Hit"]:
                if t in k:
                    tmp = acc[k].filter(regex = "^(?!.*Total)") # dont keep total counts (sum of sockets) 
                    acc[k] = tmp.rename(columns = {c : f"{t} {c}" for c in v.columns})

        acc = pd.concat(list(acc.values()), axis = 1) * 1E6

        # get access counts in percentages
        n_sockets = len(acc.columns)//2 # better way of doing this
        acc_perc = []
        for j in range(n_sockets):
            socket_counts = acc.filter(regex=f"Socket{j}")
            total = acc.filter(regex=f"Socket{j}").sum(axis=1)
            acc_perc.append(100 * socket_counts.div(total, axis = 0))

        acc_perc = pd.concat(acc_perc, axis = 1)
        access[i] = acc.reindex(sorted(acc.columns), axis=1)
        access_percent[i] = acc_perc.reindex(sorted(acc_perc.columns), axis=1)
    return access, access_percent


def cache_info_AMD(df : pd.DataFrame) -> list[pd.DataFrame]:
    """ Retrieve L2 and L3 accesses (hits and misses) and calculate percentages for AMD servers.

    Args:
        df (pd.DataFrame): uProf data.

    Returns:
        list[dict]: L2/3 access counts and access percentages.
    """
    access = {}
    access_percent = {}

    def renamer(a,b): # way to replace column names in pandas without mapping
        return lambda x: x.replace(a,b)

    for i in [2, 3]:
        cache_data = df.filter(regex = f"(?!.*from)(?=L{i})")

        total = cache_data.filter(regex = "Access")
        miss = cache_data.filter(regex = "(?!.*Latency)(?!.*%)(?=Miss)") # get the missed counts
        hit = total.rename(columns = renamer("Access","Hit")) - miss.rename(columns = renamer("Miss", "Hit")) # calculate hits from total - miss
        
        access[i] = pd.concat([miss, hit], axis=1).rename(columns = renamer(f"L{i} ", "")) # keep hits and miss, rename columns to appropriate plot labels

        if "(pti)" in access[i].columns[0]: # convert per thousand counts to just counts
            access[i] *= 1000
            access[i].rename(columns = renamer("(pti) ", ""), inplace = True)
        access[i] = access[i].reindex(sorted(access[i].columns), axis=1)

        miss_percent = cache_data.filter(regex = "Miss %") # get the miss percentage if exists
        miss_percent = miss_percent.rename(columns = renamer("% ", ""))
        if miss_percent.empty: # otherwise calculate it
            miss_percent = 100 * miss/total.rename(columns = renamer("Access", "Miss"))
            miss_percent.rename(columns = renamer("(pti) ", ""), inplace = True)

        hit_percent = 100 - miss_percent.rename(columns = renamer("Miss", "Hit")) # get hit percent
        access_percent[i] = pd.concat([miss_percent, hit_percent], axis=1).rename(columns = renamer(f"L{i} ", ""))
        access_percent[i] = access_percent[i].reindex(sorted(access_percent[i].columns), axis=1)

    return access, access_percent


def process_cache_info(intel : pd.DataFrame | None, amd : pd.DataFrame | None, out : str, test_args : dict, host : str):
    """ Process L2 and L3 cache info for either AMD or Intel servers and plot them.

    Args:
        intel (pd.DataFrame | None): pcm data.
        amd (pd.DataFrame | None): uProf data.
        out (str): Output plot directory.
        test_args (dict): Test configuration arguments.
        host (str): Host machine name.
    """
    intel_data = None
    amd_data = None
    if intel is not None:
        if all([i.empty for i in utils.search_dict(intel, f"(?=L2|L3)").values()]):
            print("No Intel PCM data captured")
            return
        else:
            intel_data = cache_info_Intel(intel)
    
    if amd is not None:
        if all([i.empty for i in utils.search_dict(amd, f"(?=L2|L3)").values()]):
            print("No AMD uProf data captured")
            return
        else:
            amd_data = cache_info_AMD(amd)


    with plotting.PlotBook(out + f"cache_plots_{host}.pdf") as book:
        for i in [intel_data, amd_data]:
            if i is None: continue
            acc = i[0]
            acc_perc = i[1]
            t0 = int(list(acc.values())[0].index[0])
            relative_time = times.relative_time(list(acc.values())[0])
            for k in acc:# acc and acc_perc should have the same keys
                plotting.plot(relative_time, acc[k], acc[k].columns, "Relative time (s)", f"L{k} cache access")
                plotting.add_metadata(test_args, t0, host = host)
                book.save()

                plotting.plot(relative_time, acc_perc[k], acc_perc[k].columns, "Relative time (s)", f"L{k} cache access (%)")
                plotting.add_metadata(test_args, t0, host = host)
                book.save()
    return


def get_thread_nums(thread_str : str) -> list[int]:
    """ Get CPU numbers from the formatted strings used in a CPU pinning file. Example is "0,10-54".

    Args:
        thread_str (str): Formatted string.

    Returns:
        list[int]: List of CPUs.
    """
    split = thread_str.split(",")

    for i in range(len(split)):
        if "-" in split[i]:
            trange = [int(j) for j in split[i].split("-")]
            split[i] = list(range(min(trange), max(trange) + 1))
        else:
            split[i] = int(split[i])
    return split


def get_readout_application_name(data : dict, hosts : list) -> list:
    """ Get the name of readout applications by parsing hdf5 files.
        #! should have a better way to do this that does not rely on the stored grafana data (maybe add a applications hdf5?)

    Args:
        data (dict): _description_
        hosts (list): _description_

    Returns:
        list: _description_
    """
    ro_data = utils.search_dict(data, "readout")["readout"]
    app_names = []
    if ro_data is not None:
        for k in ro_data:
            for h in hosts:
                matches = [i for i in k.split(" ") if h.replace("-", "") in i]
                if len(matches)> 0:
                    if matches[0] not in app_names:
                        app_names.append(matches[0])
    else:
        print("readout application name cannot be found.")
    return app_names

def parse_pinning_file(pinning_file : dict, ro_host : str, ro_app_names : list[str]) -> dict[list]:
    """ Parse a CPU pinning file, creating a list of cpus for each thread for every daq application.

    Args:
        pinning_file (dict): CPU pinning file.
        ru_host (str): Readout host name.
        ro_app_names (list[str]): Readout application names

    Returns:
        dict[list]: Parsed pinning file.
    """
    parsed_pinning_files = {}

    for t in ro_host:
        pinning = {}
        key = t.replace("-", "")
        for k, v in pinning_file.items():
            if k == "_comment" : continue
            if k == "daq_application":
                for name, application in v.items():
                    if key in name:
                        if name not in ro_app_names: continue
                        utils.add_to_dict(pinning, get_thread_nums(application["parent"]), key = "parent")
                        for tname, threads in application["threads"].items():
                            utils.add_to_dict(pinning, get_thread_nums(threads), tname)
        parsed_pinning_files[key] = pinning
    return parsed_pinning_files


def fill_zeros_with_last(arr : np.ndarray, axis : int) -> np.ndarray:
    """ Replace zeroes in an array with the previous non-zero value along a given axis.

    Args:
        arr (np.ndarray): 1 or 2 dimensional array.
        axis (int): Axis to loop over.

    Returns:
        np.ndarray: Array with the zeroes filled.
    """
    if len(arr.shape) == 1:
        return fill_zeros_with_last(np.expand_dims(arr, axis = 1), 1).flatten() # convert flat array to 2d, then flatten again.

    new = []
    for i in range(arr.shape[axis]):
        a = np.take(arr, i, axis = axis)
        prev = np.arange(len(a))
        prev[a == 0] = 0
        new.append(a[np.maximum.accumulate(prev)])
    new = np.array(new).T
    return new


def cpu_usage_rate(idle : pd.DataFrame | pd.Series, total : pd.DataFrame | pd.Series) -> np.ndarray:
    """ Compute the CPU usage as a rate per time.

    Args:
        idle (pd.DataFrame | pd.Series): Time cpu spends not doing any tasks.
        total (pd.DataFrame | pd.Series): Total cpu time.

    Returns:
        np.ndarray : Array of usage rates, has dimensions n - 1 along the time axis.
    """
    return cpu_usage(fill_zeros_with_last(abs(idle[1:].values - idle[:-1].values), axis = 1), fill_zeros_with_last(abs(total[1:].values - total[:-1].values), axis = 1))


def cpu_usage(idle : float | np.ndarray, total : float | np.ndarray) -> float | np.ndarray:
    """ CPU usage, defined as the pecrent of cpu time not idling.

    Args:
        idle (float | np.ndarray): Time cpu spends not doing any tasks.
        total (float | np.ndarray): Total cpu time.

    Returns:
        float | np.ndarray: CPU usage.
    """
    return 100 * (1 - (idle/total))


def process_cpu_info(data : dict[pd.DataFrame], out : str, test_args : dict, host : str, hw_info : dict, max_util : float = 80, pinning_file : dict | None = None):
    """ Analyse CPU information and plot the results.
        Calculates maximum, minimum and various quantiles for each core and across all cores.

    Args:
        data (dict[pd.DataFrame]): Node exporter data.
        out (str): Output directory.
        test_args (dict): Test configuration arguments.
        host (str): Host machine name.
        max_util (float): Maximum acceptable utilistation. Defaults to 80
        pinning_file (dict | None): Pinning file used for the readout application on the given host. Defaults to None.
    """

    total_time_per_core = sum(utils.search_dict(data, "(?=.*CPU)(?!.*Usage)").values()) # total time per core

    if "lstopo" not in hw_info:
        print("Note: CPU topology information not found, check lstopo output was run.")
        topology = None
    else:
        topology = cpu_topology.CoreMap(cpu_topology.create_llc_domain_map(files.read_xml(hw_info["lstopo"])))

    if total_time_per_core.empty:
        print("Warning: no CPU information was found.")
        return

    cpu_time_total = total_time_per_core.sum(axis=1) # total time across all cores
    cpu_time_idle = data["CPU idle (s)"].sum(axis=1) # total idle time across all cores
    time = total_time_per_core.sum(axis=1).index

    usage = pd.DataFrame(cpu_usage_rate(data["CPU idle (s)"], total_time_per_core), columns = total_time_per_core.columns) # usage per core
    total_usage = pd.Series(cpu_usage_rate(cpu_time_idle, cpu_time_total)) # usage of whole CPU

    # metrics for the entire CPU
    total_metrics = pd.DataFrame(np.expand_dims(np.array([
            total_usage.quantile(q = 50/100),
            total_usage.quantile(q = 99/100),
            total_usage.quantile(q = 99.9/100),
            total_usage.max(),
            total_usage.min()
        ]), axis=1), index = ["50% percentile", "99% percentile", "99.9% percentile", "Maximum", "Minimum"])

    # metrics per CPU core
    cpu_metrics = pd.concat(
        [
            usage.quantile(q = 50/100),
            usage.quantile(q = 99/100),
            usage.quantile(q = 99.9/100),
            usage.max(),
            usage.min()
        ], axis = 1, keys = ["50% percentile", "99% percentile", "99.9% percentile", "Maximum", "Minimum"])
    cpu_metrics.index = cpu_metrics.index.astype(int)

    # metrics per physical core
    physical_core_metrics = {}
    if topology:
        cpu_ids_per_core = {}
        for i, c in enumerate(topology.core.elements): # core ids are only unique per socket
            cpu_ids_per_core[i] = [p.id for p in c.children]

        core_usage = {}
        for core, num in cpu_ids_per_core.items():
            mask = np.array(num).flatten().astype(str)
            core_total_time = total_time_per_core[mask].sum(axis=1)
            core_idle_time = data["CPU idle (s)"][mask].sum(axis=1)
            core_usage[core] = cpu_usage_rate(core_idle_time, core_total_time)
        core_usage = pd.DataFrame(core_usage)
        physical_core_metrics = pd.concat(
            [
                core_usage.quantile(q = 50/100),
                core_usage.quantile(q = 99/100),
                core_usage.quantile(q = 99.9/100),
                core_usage.max(),
                core_usage.min()
            ], axis = 1, keys = ["50% percentile", "99% percentile", "99.9% percentile", "Maximum", "Minimum"])

    # metrics per thread
    thread_name_prefix = {}
    if pinning_file:
        thread_usage = {}
        for name, num in pinning_file.items():
            mask = np.array(num).flatten().astype(str)
            prefix = name.split("-")[0]
            if prefix not in thread_name_prefix:
                thread_name_prefix[prefix] = len(thread_name_prefix)
            if ("(" in name) and ("|" in name):
                if len(name.split("|")) - 2 > 3:
                    prefix = name.split("(")[0]
                    suffix = "|".join(name.split("(")[1].split(")")[0].split("|")[:3] + ["..."])
                    name = prefix + f"({suffix})"
            thread_total_time = total_time_per_core[mask].sum(axis=1)
            thread_idle_time = data["CPU idle (s)"][mask].sum(axis=1)
            thread_usage[name] = cpu_usage_rate(thread_idle_time, thread_total_time)
        thread_usage = pd.DataFrame(thread_usage)

        thread_metric = pd.concat(
            [
                thread_usage.quantile(q = 50/100),
                thread_usage.quantile(q = 99/100),
                thread_usage.quantile(q = 99.9/100),
                thread_usage.max(),
                thread_usage.min()
            ], axis = 1, keys = ["50% percentile", "99% percentile", "99.9% percentile", "Maximum", "Minimum"])

    # plotting
    with plotting.PlotBook(out + f"cpu_plots_{host}.pdf") as book:
        for c in cpu_metrics:
            plotting.bar(cpu_metrics[c].index, cpu_metrics[c], "Core", "Utilization (%)", c)
            # if max(cpu_metrics[c]) > 50:
            #     plotting.plt.axhline(max_util, color  = "k", linestyle = "--")
            plotting.add_metadata(test_args, time[0], True, host = host)
            plotting.plt.tight_layout()
            plotting.plt.subplots_adjust(top=0.9)
            book.save()

        if pinning_file:
            colours = []
            for i in thread_metric[c].index:
                colours.append(f'C{thread_name_prefix[i.split("-")[0]]}')

            for c in thread_metric:
                plotting.plt.figure(figsize=(6.4, 1.5 * 6))
                plotting.bar(thread_metric[c].index, thread_metric[c].values, "Utilization (%)", "Thread", horizontal = True, newFigure = False, title = c, colour = colours)
                # if max(cpu_metrics[c]) > 50:
                #     plotting.plt.axvline(max_util, color  = "k", linestyle = "--")

                plotting.plt.xlim(0, 100)
                plotting.add_metadata(test_args, time[0], True, host = host)
                plotting.plt.tight_layout()
                plotting.plt.subplots_adjust(top=0.9)

                handles = [mpatches.Patch(color=f"C{color}", label=prefix) for prefix, color in thread_name_prefix.items()]
                # plotting.plt.legend(handles=handles, title="Thread type", loc='upper right', bbox_to_anchor=(1.02, 1))
                plotting.plt.tight_layout()
                plotting.plt.subplots_adjust(top=0.9)
                book.save()

        plotting.bar(total_metrics.index, total_metrics.values.flatten(), None, "Total CPU Utilization (%)", None, 30, True)
        # plotting.plt.axhline(max_util, color  = "k", linestyle = "--")
        plotting.plt.ylim(0, 100)
        plotting.plt.tight_layout()
        plotting.add_metadata(test_args, time[0], False, host = host)
        plotting.plt.subplots_adjust(top=1)
        book.save()

        if topology:
            for c in physical_core_metrics:
                plotting.bar(physical_core_metrics[c].index, physical_core_metrics[c], "Physical Core", "Utilization (%)", c)
                # if max(physical_core_metrics[c]) > 50:
                #     plotting.plt.axhline(max_util, color  = "k", linestyle = "--")
                plotting.add_metadata(test_args, time[0], True, host = host)
                plotting.plt.tight_layout()
                plotting.plt.subplots_adjust(top=0.9)
                book.save()
    return


def process_disk_info(data : dict[pd.DataFrame], out : str, readout_plane : ReadoutPlane, test_args : dict, host : str):
    """ Analyse disk information for the NVME and RAID devices and plots the results.
        Calculates total IO time, disk write rate during the test and total amount written to disk.

    Args:
        data (dict[pd.DataFrame]): Node exporter data.
        out (str): Output directory.
        readout_plane (ReadoutPlane): The readout plane tested with.
        test_args (dict): Test configuration arguments.
        host (str): Host machine name.
    """
    rp = readout_plane_values[readout_plane]

    data_input = rp.adc_size * rp.adc_sampling_rate * rp.num_channels / 1E9 # adc recieved rate in Gb/s
    max_write_rp = data_input * rp.snb_readout_time / 8 # GB
    max_write_disk = rp.max_disk_write * rp.snb_readout_time # GB

    nvme_sample = data["Disk IO time (s)"].filter(regex=("nvme|md")).columns

    if nvme_sample.empty:
        print("Warning: no NVMe data was found")
        return

    time = data["Disk IO time (s)"].index.astype(int) # this is the total time elapsed
    t0 = time[0]
    time = time - t0
    tlabel = "Relative time (s)"

    dt = data["Disk IO time (s)"] - data["Disk IO time (s)"].iloc[0]
    io_time = dt[nvme_sample] # this is the time the nvme/SSD spends writing. Note that if the write rate BW is not at 100%, the disk io time does not equal the total time recording, because the disk is waiting some amount.

    # * this is not correct, as disk IO time is not the same as the total time elapsed.
    write_rate = 8 * data["Disk Written (Bps)"][nvme_sample]/(1000**3)
    total_written =  write_rate * 100 / 8

    if "Disk Total Written (B)" in data:
        total_written =  (data["Disk Total Written (B)"] - data["Disk Total Written (B)"].min(axis=0)) /(1000**3)
        total_written = total_written[nvme_sample]

    max_io = io_time.max()
    max_wr = write_rate.max()
    max_tw = total_written.max()


    with plotting.PlotBook(out + f"disk_plots_{host}.pdf") as book:
        # line plots
        plotting.plot(time, io_time, io_time.columns, tlabel, "Disk time spent during IO (s)")
        # plotting.plt.axhline(rp.snb_readout_time, color = "k", linestyle = "--", label = "Maximum\nwrite time (100 s)")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, t0, host = host)
        book.save()

        plotting.plot(time, write_rate, write_rate.columns, tlabel, "Disk write rate (Gb/s)")
        # plotting.hline(data_input, "Data input rate", "k", "--", "Gb/s")
        # plotting.hline(8 * rp.max_disk_write, "Maximum RAID write rate", "red", "--", "Gb/s")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, t0, host = host)
        book.save()
        
        plotting.plot(time, total_written, total_written.columns, tlabel, "Total written to disk (GB)")
        # plotting.plt.axhline(max_write_rp, color = "k", linestyle = "--", label = f"Minimum data written\nper {readout_plane.name} ({max_write_rp} GB)")
        # plotting.plt.axhline(max_write_disk, color = "red", linestyle = "--", label = f"Maximum data writable to disk ({max_write_disk/1000} TB)")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, t0, host = host)
        book.save()

        # bar plots
        plotting.bar(max_io.index, max_io.values, ylabel = "Device", xlabel = "Total IO time (s)", rotation = 30, bar_label = True, horizontal = True)
        # plotting.plt.axvline(rp.snb_readout_time, color = "k", linestyle = "--", label = "Maximum\nwrite time (100 s)")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, t0, host = host)
        book.save()

        plotting.bar(max_wr.index, max_wr.values, ylabel = "Device", xlabel = "Maximum Disk write rate (Gb/s)", rotation = 30, bar_label = True, horizontal = True)
        # plotting.vline(data_input, "Data input rate", "k", "--", "Gb/s")
        # plotting.vline(8 * rp.max_disk_write, "Maximum RAID write rate", "red", "--", "Gb/s")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, t0, host = host)
        book.save()

        plotting.bar(max_tw.index, max_tw.values, ylabel = "Device", xlabel = "Total written to disk (GB)", rotation = 30, bar_label = True, horizontal = True)
        # plotting.plt.axvline(max_write_rp, color = "k", linestyle = "--", label = f"Minimum data written\nper {readout_plane.name} ({max_write_rp} GB)")
        # plotting.plt.axvline(max_write_disk, color = "red", linestyle = "--", label = f"Maximum data writable to disk ({max_write_disk/1000} TB)")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, t0, host = host)
        book.save()
    return


def process_network_info(data : dict[pd.DataFrame], out : str, test_args : dict, host : str):
    """ Process system network traffic information and make plots.

    Args:
        data (dict[pd.DataFrame]): Node exporter data.
        out (str): Output file diretory.
        test_args (dict): Test configuration arguments.
        host (str): Host machine name.
    """
    network_rt = utils.search_dict(data, r"Network.*\(Bps\)")

    if all([v.empty for v in network_rt.values()]):
        print("Warning: no network data found.")
        return

    with plotting.PlotBook(out + f"network_plots_{host}") as book:
        for k, v in network_rt.items():
            plotting.plot(times.relative_time(v), v.values, v.columns, "Time (s)", k.split(" (")[0], autofmt = "B/s")
            plotting.add_metadata(test_args, int(v.index[0]), host = host)
            book.save()

            total_net = v.sum(axis=0)
            plotting.bar(total_net.index, total_net/1E6, "", "Total " + k.split(" (")[0] + " (MB)", rotation=30, bar_label = True)
            plotting.plt.yscale("log")
            plotting.add_metadata(test_args, int(v.index[0]), host = host)
            book.save()
    return


def process_tp_info(data : dict[pd.DataFrame], out : str, readout_plane : ReadoutPlane, test_args : dict):
    """ Process TP information from a given run.

    Args:
        data (dict[pd.DataFrame]): TP data.
        out (str): Output file edirectory.
        readout_plane (ReadoutPlane): The readout plane tested with.
        test_args (dict): Test configuration arguments.
    """
    rp = readout_plane_values[readout_plane]

    expected_hit_rate = min(rp.tp_rate) * rp.num_channels
    acceptance_hit_rate = max(rp.tp_rate) * rp.num_channels

    tp_data = SimpleNamespace(**{
        "hit_rates" : list(utils.search_dict(data, "hit rates").values())[0],
        "hits_sent" : list(utils.search_dict(data, "TP Sent rates").values())[0],
        "tp_writer_info" : list(utils.search_dict(data, "TP writing rates").values())[0],
        "tph_request_rates" : list(utils.search_dict(data, "(?=.*Request rate)(?!.*tphandler)").values())[0],
        "total_tp_drop_rates" : list(utils.search_dict(data, "dropped").values())[0].sum(axis = 0)
    })

    if all([getattr(tp_data, k).empty for k in vars(tp_data)]):
        print("Warning: no trigger primitive information found!")
        return

    n_dlh = rp.num_wibs * rp.num_nics
    n_rp = len(tp_data.hit_rates.columns.values) // n_dlh

    if n_rp == 0: n_rp += 1 # if we have less dlhs than expected, assume one readout plane was used for now

    total_hit_rate = tp_data.hit_rates.sum(axis = 1) # hit rate across entire detector
    total_hit_sent = tp_data.hits_sent.sum(axis = 1) # hits sent by the DLH to the trigger?

    #? code assumes readout plane channels are in ascending order, find another way to group DLHs?
    hit_rate_apa = pd.DataFrame({f"{readout_plane.name} {i}" : np.sum(tp_data.hit_rates.values[:, i * n_dlh:(i+1)*n_dlh], axis=1) for i in range(n_rp)})

    with plotting.PlotBook(out + "tp_plots") as book:
        if not total_hit_rate.empty:
            plotting.plot(times.relative_time(total_hit_rate)/10, total_hit_rate.values, f"np0{readout_plane.value} hits produced", "Time (s)", "TP rate")
            plotting.plot(times.relative_time(total_hit_sent)/10, total_hit_sent.values, f"np0{readout_plane.value} hits sent", "Time (s)", "TP rate", newFigure = False, autofmt = "Hz")
        
            # plotting.hline(expected_hit_rate * n_rp, "expected hit rate", "red", "--", "Hz")
            # plotting.hline(acceptance_hit_rate * n_rp, "acceptence hit rate", "k", "--", "Hz")
            plotting.plt.legend(fontsize="x-small")
            plotting.add_metadata(test_args, int(total_hit_rate.index[0]))
            book.save()

        if not hit_rate_apa.empty:
            plotting.plt.figure()
            for c in hit_rate_apa:
                plotting.plot(times.relative_time(hit_rate_apa[c])/10, hit_rate_apa[c].values, c, "Time (s)", "TP rate", newFigure = False, autofmt = "Hz")
            # plotting.hline(expected_hit_rate, f"expected hit rate per {readout_plane.name}", "red", "--", "Hz")
            # plotting.hline(acceptance_hit_rate, f"acceptence hit rate per {readout_plane.name}", "k", "--", "Hz")
            plotting.plt.legend(fontsize="x-small")
            plotting.add_metadata(test_args, int(hit_rate_apa[c].index[0]))
            book.save()

        if not tp_data.tp_writer_info.empty:
            plotting.plot(times.relative_time(tp_data.tp_writer_info)/10, tp_data.tp_writer_info[["TP Received", "TP written"]], ["received", "written"], "Time (s)", "TP rate", autofmt = "Hz")
            plotting.plt.title("TPWriter receieve/write rates")
            # plotting.hline(expected_hit_rate * n_rp, "expected hit rate", "red", "--", "Hz")
            # plotting.hline(acceptance_hit_rate * n_rp, "acceptence hit rate", "k", "--", "Hz")
            plotting.plt.legend(fontsize="x-small")
            plotting.add_metadata(test_args, int(tp_data.tp_writer_info.index[0]))
            book.save()

            plotting.plot(times.relative_time(tp_data.tp_writer_info)/10, rp.tp_size * tp_data.tp_writer_info[["TP Received", "TP written"]], ["received", "written"], "Time (s)", "Rate", autofmt = "b/s")
            plotting.plt.title("TPWriter receieve/write rates")
            # plotting.hline(expected_hit_rate * n_rp * rp.tp_size, "expected hit rate", "red", "--", "b/s")
            # plotting.hline(acceptance_hit_rate * n_rp * rp.tp_size, "acceptence hit rate", "k", "--", "b/s")
            plotting.plt.legend(fontsize="x-small")
            plotting.add_metadata(test_args, int(tp_data.tp_writer_info.index[0]))
            book.save()

        if not tp_data.total_tp_drop_rates.empty:
            plotting.bar(tp_data.total_tp_drop_rates.index, tp_data.total_tp_drop_rates.values, "", "Number of TPs", "TPs dropped", bar_label = True)
            plotting.plt.ylim(0)
            plotting.add_metadata(test_args, int(tp_data.tp_writer_info.index[0]))
            book.save()

        if not tp_data.tph_request_rates.empty:
            plotting.plot(times.relative_time(tp_data.tph_request_rates)/10, tp_data.tph_request_rates.values, tp_data.tph_request_rates.columns, "Time (s)", "Request Rates", autofmt = "Hz")
            plotting.add_metadata(test_args, int(tp_data.tp_writer_info.index[0]))
            book.save()

        if not tp_data.tph_request_rates.empty:
            request_rate_percent = tp_data.tph_request_rates.sum(axis=0)
            request_rate_percent = request_rate_percent.div(request_rate_percent["Total "], axis = 0)
            request_rate_percent.pop("Total ")
            plotting.bar(request_rate_percent.index, request_rate_percent, "Requst type", "Requests (%)", "Total number of requests", bar_label = True)
            plotting.add_metadata(test_args, int(tp_data.tp_writer_info.index[0]))
            book.save()
    return


def process_frontend_info(data : dict[pd.DataFrame], out : str, readout_plane : ReadoutPlane, test_args : dict):
    """ Process frontend readout information and make plots.

    Args:
        data (dict[pd.DataFrame]): Node exporter data.
        out (str): Output file diretory.
        readout_plane (ReadoutPlane): The readout plane tested with.
        test_args (dict): Test configuration arguments.
    """
    rx_throughput = list(utils.search_dict(data, "Throughput").values())[0] # bytes recevied from each queue in a readout application
    if rx_throughput.empty:
        print("Warning: no frontend ethernet data was found!")
        return
    start_time = int(rx_throughput.index[0])
    UDPQueue = namedtuple("UDPQueue", ["element", "subelement", "queue"])

    dict_cols = {}
    old_fmt = False
    for c in rx_throughput.columns:
        literal = ast.literal_eval(c)
        if "application" in literal: # this is older style of frontend data, so it needs to be reformatted
            literal["element"] = literal.pop("application")
            literal["subelement"] = None # did not exist in old format
            old_fmt = True
        dict_cols[c] = UDPQueue(**literal)
    rx_throughput = rx_throughput.rename(columns = dict_cols)

    rp = readout_plane_values[readout_plane]

    adc_data_stream_rate_per_ch = rp.adc_size * rp.adc_sampling_rate / 8 # B/s

    max_rate_per_stream = rp.channels_per_queue * adc_data_stream_rate_per_ch # B/s

    unique_element = np.unique([c.element for c in rx_throughput.columns])
    if old_fmt:
        app_names = [i.element for i in dict_cols.values()]
    else:
        app_names = [i.split("-")[1] for i in unique_element]


    rx_throughput_elems = {}
    queue_nums = []
    for elem in unique_element:
        app_queues = [rx_throughput[c] for c in rx_throughput.columns if c.element == elem]
        queue_nums.append(len(app_queues))
        rx_throughput_elems[elem] = sum(app_queues)

    rx_throughput_elems = pd.DataFrame(rx_throughput_elems)

    if len(queue_nums) > 1:
        print("Warning: rx queue number for applications differ, will use the first to calculate expected rate.")
    n_queues_per_elem = queue_nums[0]

    # input + missed = total
    input_packets = sum_over_app(data["Input Packets"], app_names)
    input_missed_packets = sum_over_app(data["Input Missed Packets"], app_names)
    rx_dropped_packets = sum_over_app(data["RX Dropped Packets"], app_names)
    total_packets = input_packets + input_missed_packets

    with plotting.PlotBook(out + "fe_plots") as book:

        plotting.plot(times.relative_time(rx_throughput_elems)/10, rx_throughput_elems, rx_throughput_elems.columns, "Time (s)", "RX throughput", autofmt = "B/s")
        # plotting.hline(max_rate_per_stream * n_queues_per_elem, "Acceptance data input", autofmt = "B/s", linestyle = "--")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, start_time)
        book.save()

        if len(input_missed_packets) > 0:
            plotting.plot(times.relative_time(input_missed_packets)/10, 100*input_missed_packets/total_packets, input_missed_packets.columns, "Time (s)", "Missed Packets (%)")
            plotting.add_metadata(test_args, start_time)
            book.save()

            plotting.plot(times.relative_time(input_missed_packets)/10, 100*rx_dropped_packets/total_packets, rx_dropped_packets.columns, "Time (s)", "Dropped Packets (%)")
            plotting.add_metadata(test_args, start_time)
            book.save()
        else:
            print("Note: no missing/dropped packe info was found.")

        plotting.plot(times.relative_time(rx_throughput)/10, rx_throughput, None, "Time (s)", "RX throughput", autofmt = "B/s")
        # plotting.hline(max_rate_per_stream, "Acceptance data input", autofmt = "B/s", linestyle = "--")
        plotting.plt.legend(fontsize="x-small")
        plotting.add_metadata(test_args, start_time)
        book.save()

        total_errors = {k : v.sum(axis=0) for k,v in utils.search_dict(data, "(?=.*RX)(?=.*Error)(?!.*Queue)").items()}
        label =  [f"{readout_plane.name} {i}" for i, _ in enumerate(list(total_errors.values())[0].index)]
        for k, v in total_errors.items():
            plotting.bar(label, v.values, None, k, bar_label = True)
            plotting.plt.ylim(0)
            plotting.add_metadata(test_args, start_time, False)
            book.save()

        total_dropped_frames = {f"{readout_plane.name} {i}" : v.sum().sum() for i, v in enumerate(utils.search_dict(data, "RX Dropped Frames").values())}
        plotting.bar(list(total_dropped_frames.keys()), list(total_dropped_frames.values()), None, "RX Dropped Frames", bar_label = True)
        plotting.plt.ylim(0)
        plotting.add_metadata(test_args, start_time)
        book.save()

        total_errors_dlh = {}
        for k, v in utils.search_dict(data, "Total errors").items():
            key = [i for i in app_names if i in k][0]
            total_errors_dlh[key] = v.sum().sum()
        plotting.bar(list(total_errors_dlh.keys()), list(total_errors_dlh.values()), None, "Errors from DLH", bar_label = True)
        plotting.plt.ylim(0)
        plotting.add_metadata(test_args, start_time)
        book.save()
    return


def process_readout_info(data : dict[pd.DataFrame], out : str, test_args : dict):
    """ Process frontend readout information and make plots.

    Args:
        data (dict[pd.DataFrame]): Node exporter data.
        out (str): Output file diretory.
        test_args (dict): Test configuration arguments.
    """
    request_rates_total = list(utils.search_dict(data, "(?=.*Request rates)(?!.*for)").values())[0]

    if request_rates_total.empty:
        print("Warning: no readout request rate information found!")
        return

    request_rates_dlh = utils.search_dict(data, "(?=.*Request rates)(?=.*for)")

    mean_request_rate_dlh = pd.DataFrame({k : v.mean(axis=0) for k,v in request_rates_dlh.items()})
    mean_request_rate_dlh.rename(columns = {k : k.split(" ")[-1] for k in request_rates_dlh}, inplace = True)

    with plotting.PlotBook(out + "re_plots") as book:
        plotting.plot(times.relative_time(request_rates_total)/10, request_rates_total, request_rates_total.columns, "Time (s)", "request rate (Hz)")
        plotting.add_metadata(test_args, int(request_rates_total.index[0]))
        book.save()

        plotting.bar(request_rates_total.columns, request_rates_total.sum(axis=0), "", "Total requests", rotation = 30)
        plotting.add_metadata(test_args, int(request_rates_total.index[0]))
        book.save()

        plotting.bar(request_rates_total.columns, request_rates_total.mean(axis=0), "", "Average request rate (Hz)", rotation = 30)
        plotting.add_metadata(test_args, int(request_rates_total.index[0]))
        book.save()

        plotting.bar(request_rates_total.columns, request_rates_total.mean(axis=0) // len(mean_request_rate_dlh.columns), "", "Average request rate (Hz)", rotation = 30)
        plotting.add_metadata(test_args, int(request_rates_total.index[0]))
        book.save()
    return


def process_daq_overview_info(data : dict[pd.DataFrame], out : str, test_args : dict):
    """ Process daq overview information and make plots.

    Args:
        data (dict[pd.DataFrame]): Node exporter data.
        out (str): Output file diretory.
        test_args (dict): Test configuration arguments.
    """
    global_trigger_rate = data["Global Trigger Rate"]
    dataflow_written_rate = data["Data Writers Information"].sort_index() # not sure what happened here

    if global_trigger_rate.empty and dataflow_written_rate.empty:
        print("Warning : no DAQ overview data found!")
        return

    with plotting.PlotBook(out + "ov_plots") as book:
        total_count = global_trigger_rate.pop("Total count")
        plotting.plot(times.relative_time(global_trigger_rate)/10, global_trigger_rate, global_trigger_rate.columns, "Time (s)", "Global Trigger Rate", autofmt = "Hz")
        plotting.plt.legend(ncols = 2, loc = "upper left", fontsize="x-small")
        plotting.plt.gca().grid(False)
        lim = plotting.plt.gca().get_ylim()
        plotting.plt.ylim(min(lim), 1.2 * max(lim))

        ax_total = plotting.plt.gca().twinx()
        ax_total.plot(times.relative_time(global_trigger_rate)/10, total_count, linestyle = "--", color = f"C{len(global_trigger_rate.columns)}", label = "Total triggers", zorder = -1)
        ax_total.set_ylabel("Total count")
        ax_total.grid(False)
        plotting.plt.legend(loc = "upper right", fontsize="x-small")

        lim = plotting.plt.gca().get_ylim()
        plotting.plt.ylim(min(lim), 1.2 * max(lim))
        plotting.add_metadata(test_args, int(global_trigger_rate.index[0]))
        book.save()

        plotting.plot(times.relative_time(global_trigger_rate)/10, global_trigger_rate, global_trigger_rate.columns, "Time (s)", "Global Trigger Rate", autofmt = "Hz")
        lim = plotting.plt.gca().get_ylim()
        plotting.plt.ylim(min(lim), 1.2 * max(lim))
        plotting.add_metadata(test_args, int(global_trigger_rate.index[0]))
        book.save()

        plotting.plot(times.relative_time(dataflow_written_rate)/10, dataflow_written_rate, dataflow_written_rate.columns, "Time (s)", "Data written by Dataflow", autofmt = "B/s")
        plotting.plt.legend(ncols = 2, fontsize="x-small")
        lim = plotting.plt.gca().get_ylim()
        plotting.plt.ylim(min(lim), 1.2 * max(lim))
        plotting.add_metadata(test_args, int(global_trigger_rate.index[0]))
        book.save()
    return


def process_message_report(data : dict[pd.DataFrame], out : str, test_args : dict):
    mr = data["Message Reporting"]
    if mr.empty:
        print("Note: no ERS messages were found.")
        return
    else:
        with plotting.PlotBook(out + "message_reporting") as book:
            _, ax = plotting.plt.subplots()
            ax.axis('off')
            mr.index = pd.to_datetime(pd.to_datetime(mr.index.values, unit = "s", origin = "unix"))
            pd.plotting.table(ax, mr, loc='center', cellLoc='center')
            plotting.add_metadata(test_args, int(data["Global Trigger Rate"].index[0]))
            book.save()
    return


def simplify_dict_name(dictionary : dict, default : dict):
    """ Simplify keys in the loaded data dictionary.

    Args:
        dictionary (dict): Data dictionary.
    """
    unique_names = utils.get_unique_string_elements(list(dictionary.keys()), "_")
    for old, new in zip(list(dictionary.keys()), unique_names):
        if len(new) == 0:
            k = default
        else:
            k = new
        dictionary[k] = dictionary.pop(old)
    return


def analyse_data(test_args : dict):
    plotting.set_plot_style()

    expected_dashboards = files.read_json(f"{os.environ['PERFORMANCE_TEST_PATH']}/config/dashboard_info.json")["dashboard_uid"]

    hw_info = shell.search_data_file("xml", test_args["data_path"])
    if len(hw_info) > 0:
        hw_info = {
            h : {k : v for v, k in zip(hw_info, utils.get_unique_string_elements([s.stem for s in hw_info if h in s.stem], "_"))}
            for h in test_args["host"]
        }
    else:
        print("Warning: hardware information not found.")
        hw_info = None

    tr = time_range(*test_args["time_range"])

    data = utils.search_hdf5_data(test_args["data_path"], test_args["dunedaq_version"])
    print(data)

    for d in data:
        if data[d]:
            data[d] = times.slice_time_range(files.read_hdf5(data[d]), tr)

    if test_args["plot_path"]:
        out = test_args["plot_path"] + "analysis/"
    else:
        out = utils.make_plot_dir(test_args) + "analysis/"
    os.makedirs(out, exist_ok = True)

    ro_apps = get_readout_application_name(data, test_args["host"])

    pinning_file = shell.search_data_file("cpupin-all-running", test_args["data_path"])
    if len(pinning_file) == 0:
        pinning_file = None
    else:
        pinning_file = files.read_json(pinning_file[0])

    if pinning_file:
        pinning_file = parse_pinning_file(pinning_file, test_args["host"], ro_apps)


    if ("crp" in test_args["data_source"].lower()) or ("np02" in test_args["data_source"].lower()):
        readout_plane = ReadoutPlane.CRP
    elif ("apa" in test_args["data_source"].lower()) or ("np04" in test_args["data_source"].lower()):
        readout_plane = ReadoutPlane.APA
    else:
        print(f"cannot infer readout plane type based on data_source: {test_args['data_source']}, default to APA.")
        readout_plane = ReadoutPlane.APA

    if len(test_args["host"]) == 1:
        def_name = test_args["host"][0].replace("-", "")
    else:
        def_name = None
    intel_pcm = utils.search_dict(data, "A_CvwTCWk")
    simplify_dict_name(intel_pcm, def_name)
    uprof = utils.search_dict(data, "uprof-pcm")
    simplify_dict_name(uprof, def_name)
    node_exporter = utils.search_dict(data, "node-exporter")
    simplify_dict_name(node_exporter, def_name)

    for k, v in intel_pcm.items():
        if v is not None:
            process_cache_info(v, None, out, test_args, k.replace("srv", "-srv-"))

    for k, v in uprof.items():
        if v is not None:
            process_cache_info(None, v, out, test_args, k.replace("srv", "-srv-"))

    for k, v in node_exporter.items():
        h = k.replace("srv", "-srv-")
        if pinning_file:
            pf = pinning_file.get(k)
        else:
            pf = None
        process_cpu_info(v, out, test_args, h, hw_info[h], pinning_file = pf)

        process_disk_info(v, out, readout_plane, test_args, h)

        process_network_info(v, out, test_args, h)

    for h in test_args["host"]:
        k = h.replace("-", "")
        if k not in node_exporter:
            print(f"Warning: no node exporter data captured for {h}")
            continue
        process_memory_info(node_exporter.get(k), intel_pcm.get(k), uprof.get(k), out, hw_info[h], test_args, h)

    process_frontend_info(data["frontend_ethernet"], out, readout_plane, test_args)

    tph = data["tp_handlers"]
    if tph is None: tph = {} # tp_handler dashboard did not exist in old grafana format
    process_tp_info(data["trigger_primitives"] | tph, out, readout_plane, test_args)

    for d, func in zip(["readout", "overview", "overview"], [process_readout_info, process_daq_overview_info, process_message_report]):
        if d not in expected_dashboards: continue
        func(data[d], out, test_args)
    return


def main(args : argparse.Namespace):
    test_args = files.read_config(args.file)
    analyse_data(test_args)
    return


if __name__ == "__main__":
    args = utils.ApplicationArguments("Analyse performance metrics.").create()
    main(args)